{% set name = "st-annotated-text" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/st-annotated-text/st_annotated_text-4.0.2.tar.gz
  sha256: b0134dcf734697cc3dbdb11862c4174071e7fb6f365af55a37c710d357fd88a5

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<35]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - htbuilder
    - streamlit

test:
  imports:
    - annotated_text
    - annotated_text.parameters
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://github.com/tvst/st-annotated-text
  dev_url: https://github.com/tvst/st-annotated-text
  doc_url: https://github.com/tvst/st-annotated-text/blob/master/README.md
  summary: A simple component to display annotated text in Streamlit apps.
  description: |
    A simple component to display annotated text in Streamlit apps.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - ELundby45
